### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by andresloopear** [wnyc/cordova-plugin-playerhater#13]
Hi there, I'm trying to make this plugin work on cordova, building for android, and testing on android 5.0.1.
I resolved compilation errors based on some other issues already closed, and build is successful.
My testing code uses the code defined in this repository usage section, within deviceready function, :

onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },
receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');
        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');
        console.log('Received Event: ' + id);

```
    window.audioplayer.configure( successCallback, failureCallback);
    window.audioplayer.playstream( successCallback, failureCallback,
        // stream urls to play on android/ios
        {
            android: "http://fm939.wnyc.org/wnycfm-app.aac",
            ios: "http://fm939.wnyc.org/wnycfm-app.aac"
        },
        // metadata used for iOS lock screen, Android 'Now Playing' notification
        {
            "title": "Cuomo; NJ Candidates; and Candy Etiquette",
            "artist": "The Brian Lehrer Show",
            "image": {
            "url": "https://media2.wnyc.org/i/300/300/l/80/1/governor_andrew_cuomo.jpg"
        },
            "imageThumbnail": {
            "url": "https://media2.wnyc.org/i/60/60/l/80/1/governor_andrew_cuomo.jpg"
        },
            "name": "WNYC 93.9 FM",
            "description": "News, Culture & Talk"
        },
        // javascript-specific json represenation of audio to be played, which will be passed back to
        // javascript via successCallback when a stream is launched from a local notification (eg, the alarm clock
        extra
    );
}
```

Application loads on android but it does nothing, no sound nor notification message.
Can you help me?

**Comment by BenasPaulikas** [comment]
@andresloopear Hey, did you find out how to make it work ? When doing window.audioplayer.configure( successCallback, failureCallback); I get that window.audioplayer is undefined..

**Comment by andresloopear** [comment]
@BenasPaulikas Hi, after some hours of debugging I couldn't make it work, ended changing library.

**Comment by BenasPaulikas** [comment]
And you changed to .. ?

**Comment by andresloopear** [comment]
First tried to use HTML5 Audio class, but found an error on Android 4.2.2 witch wouldn't play any sound. Ended making a custom plugin.

**Comment by BenasPaulikas** [comment]
Talking about this "cordova-plugin-playerhater" what do you get when doing console.log(window.audioplayer) ?
