### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by lnaghash** [wnyc/cordova-plugin-playerhater#3]
hi,
when I'm trying to build it on new cordova for android platform it get those error:
\platforms\android\src\org\prx\playerhater\util\Config.java:24: error: cannot find symbol
import org.prx.playerhater.R;
                          ^
  symbol:   class R
  location: package org.prx.playerhater
\platforms\android\src\org\prx\playerhater\plugins\ExpandableNotificationPlugin.java:24: error: cannot find symbol
import org.prx.playerhater.R;
                          ^
  symbol:   class R
  location: package org.prx.playerhater
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:30: error: cannot find symbol
import org.prx.playerhater.R;
                          ^
  symbol:   class R
  location: package org.prx.playerhater
\platforms\android\src\org\prx\playerhater\util\Log.java:18: error: cannot find symbol
import org.prx.playerhater.BuildConfig;
                          ^
  symbol:   class BuildConfig
  location: package org.prx.playerhater
\platforms\android\src\org\prx\playerhater\util\Config.java:85: error: package R does not exist
                            R.xml.zzz_ph_config_defaults);
                             ^
\platforms\android\src\org\prx\playerhater\ipc\PlayerHaterServer.java:29: error: PlayerHaterServer is not abstract and does not override abstract method enqueueAtP
int) in IPlayerHaterServer
public class PlayerHaterServer extends IPlayerHaterServer.Stub {
       ^
\platforms\android\src\org\prx\playerhater\ipc\PlayerHaterServer.java:93: error: method does not override or implement a method from a supertype
    @Override
    ^
\platforms\android\src\org\prx\playerhater\ipc\PlayerHaterServer.java:103: error: method does not override or implement a method from a supertype
    @Override
    ^
\platforms\android\src\org\prx\playerhater\ipc\PlayerHaterServer.java:108: error: method does not override or implement a method from a supertype
    @Override
    ^
\platforms\android\src\org\prx\playerhater\ipc\ServerPlayerHater.java:82: error: method play in interface IPlayerHaterServer cannot be applied to given types;
                    return mServer.play(SongHost.getTag(song), Songs.toBundle(song), 0);
                                  ^
  required: int,int
  found: int,Bundle,int
  reason: actual and formal argument lists differ in length
\platforms\android\src\org\prx\playerhater\ipc\ServerPlayerHater.java:92: error: method play in interface IPlayerHaterServer cannot be applied to given types;
                    return mServer.play(SongHost.getTag(song), Songs.toBundle(song), startTime);
                                  ^
  required: int,int
  found: int,Bundle,int
  reason: actual and formal argument lists differ in length
\platforms\android\src\org\prx\playerhater\ipc\ServerPlayerHater.java:112: error: method enqueue in interface IPlayerHaterServer cannot be applied to given types;
                    return mServer.enqueue(SongHost.getTag(song), Songs.toBundle(song));
                                  ^
  required: int
  found: int,Bundle
  reason: actual and formal argument lists differ in length
\platforms\android\src\org\prx\playerhater\ipc\ServerPlayerHater.java:122: error: method enqueueAtPosition in interface IPlayerHaterServer cannot be applied to giv

                    mServer.enqueueAtPosition(position, SongHost.getTag(song), Songs.toBundle(song));
                           ^
  required: int,int
  found: int,int,Bundle
  reason: actual and formal argument lists differ in length
\platforms\android\src\org\prx\playerhater\plugins\NotificationPlugin.java:79: error: cannot find symbol
           int closeResId = activityRes.getIdentifier("zzz_ph_ic_notification", "drawable", cordova.getActivity().getPackageName());
                                                                                            ^
  symbol:   variable cordova
  location: class NotificationPlugin
\platforms\android\src\org\prx\playerhater\plugins\NotificationPlugin.java:79: error: cannot find symbol
           int closeResId = activityRes.getIdentifier("zzz_ph_ic_notification", "drawable", cordova.getActivity().getPackageName());
                            ^
  symbol:   variable activityRes
  location: class NotificationPlugin
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:52: error: package R does not exist
        setTextViewText(R.id.zzz_ph_notification_title, title);
                         ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:58: error: package R does not exist
        setTextViewText(R.id.zzz_ph_notification_text, artist);
                         ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:65: error: package R does not exist
        setImageViewUri(R.id.zzz_ph_notification_image, mNotificationImageUrl);
                         ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:76: error: package R does not exist
        setImageViewResource(R.id.zzz_ph_play_pause_button,
                              ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:77: error: package R does not exist
                R.drawable.zzz_ph_bt_play);
                 ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:82: error: package R does not exist
        setImageViewResource(R.id.zzz_ph_play_pause_button,
                              ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:83: error: package R does not exist
                R.drawable.zzz_ph_bt_pause);
                 ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:91: error: package R does not exist
                setViewEnabled(R.id.zzz_ph_skip_button, false);
                                ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:93: error: package R does not exist
                setViewEnabled(R.id.zzz_ph_skip_button, true);
                                ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:97: error: package R does not exist
                setViewEnabled(R.id.zzz_ph_back_button, false);
                                ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:99: error: package R does not exist
                setViewEnabled(R.id.zzz_ph_back_button, true);
                                ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:123: error: package R does not exist
            mNotificationView.setTextViewText(R.id.zzz_ph_notification_title,
                                               ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:125: error: package R does not exist
            mNotificationView.setTextViewText(R.id.zzz_ph_notification_text,
                                               ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:128: error: package R does not exist
                setImageViewUri(R.id.zzz_ph_notification_image,
                                 ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:141: error: package R does not exist
        view.setOnClickPendingIntent(R.id.zzz_ph_skip_button,
                                      ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:143: error: package R does not exist
        view.setOnClickPendingIntent(R.id.zzz_ph_play_pause_button,
                                      ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:145: error: package R does not exist
        view.setOnClickPendingIntent(R.id.zzz_ph_stop_button,
                                      ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:147: error: package R does not exist
        view.setOnClickPendingIntent(R.id.zzz_ph_back_button,
                                      ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:153: error: package R does not exist
                R.layout.zzz_ph_hc_notification);
                 ^
\platforms\android\src\org\prx\playerhater\plugins\TouchableNotificationPlugin.java:171: error: package R does not exist
                .setSmallIcon(R.drawable.zzz_ph_ic_notification)
                               ^
\platforms\android\src\org\prx\playerhater\plugins\ExpandableNotificationPlugin.java:43: error: package R does not exist
                    R.layout.zzz_ph_jbb_notification);
                     ^
\platforms\android\src\org\prx\playerhater\plugins\ExpandableNotificationPlugin.java:45: error: package R does not exist
            mExpandedView.setTextViewText(R.id.zzz_ph_notification_title,
                                           ^
\platforms\android\src\org\prx\playerhater\plugins\ExpandableNotificationPlugin.java:47: error: package R does not exist
            mExpandedView.setTextViewText(R.id.zzz_ph_notification_text,
                                           ^
\platforms\android\src\org\prx\playerhater\plugins\ExpandableNotificationPlugin.java:49: error: package R does not exist
            mExpandedView.setImageViewUri(R.id.zzz_ph_notification_image,

**Comment by 5inline** [comment]
I'm getting the same issue.

**Comment by toontoet** [comment]
Replace all occurrences of org.prx.playerhater.R with your.app.packagename.R

**Comment by 5inline** [comment]
Thanks, that fixed those specific issues. Next set of errors are:

```
    ~/cordova/platforms/android/src/org/prx/playerhater/util/Log.java:18: error: package .android.playerhater does not exist
    import org.prx.android.playerhater.BuildConfig;
                                      ^
    ~/cordova/platforms/android/src/org/prx/playerhater/util/Log.java:25: error: cannot mbol
    		if (BuildConfig.DEBUG) {
    		    ^
      symbol:   variable BuildConfig
      location: class Log
    ~/cordova/platforms/android/src/org/prx/playerhater/util/Log.java:25: error: illegal  type
    		if (BuildConfig.DEBUG) {
    		   ^
    ~/cordova/platforms/android/src/org/prx/playerhater/util/Log.java:31: error: cannot mbol
    		if (BuildConfig.DEBUG) {
    		    ^
      symbol:   variable BuildConfig
      location: class Log
    ~/cordova/platforms/android/src/org/prx/playerhater/util/Log.java:31: error: illegal  type
    		if (BuildConfig.DEBUG) {
    		   ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
```

**Comment by toontoet** [comment]
Same there, replace org.prx.android.playerhater.BuildConfig with your.app.packagename.BuildConfig.

Would love to know how to fix it without using your own packagename.

**Comment by 5inline** [comment]
That solved this issue. Thanks.
