### ISSUE TITLE
iOS Build Fails

### ISSUE THREAD

**Issue by 5inline** [wnyc/cordova-plugin-playerhater#6]
In XCode, the build error is:
'Reachability.h' not found in 'ReachabilityManager.h'

**Comment by toontoet** [comment]
There are two files missing in the config.xml file of the plugin. Add:

<header-file src="src/ios/Reachability/Reachability.h" />
<source-file src="src/ios/Reachability/Reachability.m" />

To get it to work in iOS.

**Comment by 5inline** [comment]
Thanks for responding. I don't see anything in your message after "Add:" though?

**Comment by toontoet** [comment]
Let try it again:

`<header-file src="src/ios/Reachability/Reachability.h" />
<source-file src="src/ios/Reachability/Reachability.m" />`

**Comment by 5inline** [comment]
Thanks! That worked.
